name: Update Version and Commit on Merge

on:
    push:
        branches: [ generate-version-numbers-with-gh-actions ]

jobs:
    update_version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set version environment variables
            run: echo "VERSION_MAJOR=${{ secrets.VERSION_MAJOR }}" >> $GITHUB_ENV
            - name: Count merges and commits
            run: |
                minor=$(git rev-list --merges --count generate-version-numbers-with-gh-actions)
                revision=$(git rev-list --count HEAD)
                echo "MINOR=$minor" >> $GITHUB_ENV
                echo "REVISION=$revision" >> $GITHUB_ENV
            - name: Generate version number
            run: |
                major=${{ env.VERSION_MAJOR }}
                minor=${{ env.MINOR }}
                revision=${{ env.REVISION }}
                version="$major.$minor.$revision"
                echo "VERSION=$version" >> $GITHUB_ENV
            - name: Set environment variables from $GITHUB_ENV
            run: |
                echo $(env | grep '^GITHUB_')
                env | grep '^GITHUB_' >> $GITHUB_ENV
            # - name: Update footer version
            # run: python write_version_number.py "${{ github.sha }}"
            # - name: Add and commit changes
            # run: |
            #     git config user.name 'GitHub Actions'
            #     git config user.email 'github-actions[bot]@users.noreply.github.com'
            #     git add index.html
            #     git commit -m "Update footer version to $VERSION"
            #     git push origin staging 