name: Update Version and Commit on Merge

on:
    push:
        branches: [ generate-version-numbers-with-gh-actions ]

jobs:
    update_version:
        runs-on: ubuntu-latest
        env:
            BRANCH: generate-version-numbers-with-gh-actions    
        steps:
            - uses: actions/checkout@v3
            - name: Count merges and commits
              run: |
                minor=$(git rev-list --merges --count $BRANCH)
                revision=$(git rev-list --count $BRANCH)
                echo "MINOR=$minor" >> $GITHUB_ENV
                echo "REVISION=$revision" >> $GITHUB_ENV
            - name: Generate version number
              run: |
                major=${{ vars.VERSION_MAJOR }}
                minor=${{ env.MINOR }}
                revision=${{ env.REVISION }}
                version="$major.$minor.$revision"
                echo "VERSION=$version" >> $GITHUB_ENV

            - name: Update footer version
              run: python .github/scripts/write_version_number.py "${{ env.VERSION }}"
            - name: Add and commit changes
              run: |
                git config user.name 'GitHub Actions'
                git config user.email 'github-actions[bot]@users.noreply.github.com'
                git add index.html
                git commit -m "Update footer version to $VERSION"
                git push origin staging 