name: Update Version Number

on:
    push:
        branches: [ staging ]

jobs:
    update_version:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: python -m pip install beautifulsoup4
            - name: Set version environment variables
              run: |
                # Set major version manually based on your release process
                echo "VERSION_MAJOR=0" >> $GITHUB_ENV
                # Set minor version based on tag presence
                if git tag --contains master | grep -q "v[0-9]+.[0-9]+"; then
                    # Assume tags follow format 'vX.Y', increment minor
                    version=$(git tag --contains master | grep -oE "v[0-9]+.[0-9]+" | head -1)
                    major=$(echo $version | cut -d'.' -f1)
                    minor=$(($(echo $version | cut -d'.' -f2) + 1))
                    echo "VERSION_MINOR=$minor" >> $GITHUB_ENV
                fi
            - name: Update version number
              run: python rev_version_number.py "${{ github.repository }}" "${{ github.ref }}"